### PR TITLE
Addon install script for Linux.

### PR DESCRIPTION
**Pull request by MatusGuy**
It installs to the system.

### CODE REVIEW

**Comment by tylerandari13** [comment]
running-away-genitals

**Comment by Frostwithasideofsalt** [comment]
fuck you

**Review by Frostwithasideofsalt — COMMENTED** [review]
: 3

**Review by bruhmoent — CHANGES_REQUESTED** [review]
not enough removing.

**Review by tylerandari13 — APPROVED** [review]
2F303EFC-3A75-4EA1-B4D6-50EF57A688B0

**Comment by tylerandari13** [comment]
YIPPEE

**Pull request merged**
